version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  pgadmin:
      ports:
          - "8080:80"
      environment:
          - PGADMIN_DEFAULT_EMAIL=user@domain.com
          - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      container_name: pgadmin
      image: dpage/pgadmin4